# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test and build pwp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  Test_and_build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12.0
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.0"

    #Display python version
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Install browsers
      run: playwright install

    - name: UI
      run: xvfb-run python


    - name: Test with pytest
      run: pytest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        context: .
        push: true
        tags: ghcr.io/jonramart/playwright-with-pytest:latest
